spring:
  application:
    name: Test-Config  # This will be overridden if imported from Git

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Fixed: Full Eureka registry URL

# Optional: Local fallback props (e.g., if Config Server is down)
server:
  port: 7074  # Adjust as needed
